# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_auto_20160413_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_picture',
            name='Home',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='MAIN.Home'),
            preserve_default=False,
        ),
    ]
