# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_home_picture_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='Category',
            new_name='Drink_category',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Category',
            new_name='Food_category',
        ),
    ]
