# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 18:53
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_auto_20160413_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_picture',
            name='image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='illustration Home'),
        ),
    ]
