# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_auto_20160414_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='baseline',
            field=models.TextField(blank=True, default=False),
        ),
    ]
